### ISSUE TITLE
add a hotkey to add new tags

### ISSUE THREAD

**Issue by Shelbyen** [j2k-company/input-post-processor#5]
When you select text and use keyboard shortcuts, a console appears in which you enter the name of a new tag

**Comment by Shelbyen** [comment]
Should I program then? I'm not the developer)

**Comment by jaka2005** [comment]
ok, it's really good idea, i think it will be added to the roadmap

**Comment by jaka2005** [comment]
> Should I program then? I'm not the developer)

what?

**Comment by Shelbyen** [comment]
> > Should I program then? I'm not the developer)
> 
> what?

not a developer YET)))
